apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name.service }}
  labels:
    {{- include "gongsiin_institute.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: tomcat-port
      nodePort: 30033
  selector:
    {{- include "gongsiin_institute.selectorLabels" . | nindent 4 }}
